import java.sql.*;

public class Activity {
	private Timestamp time;
	private String account;
	private String event;

	public Activity(String account, String event, Timestamp time) {
		this.time = time;
		this.account = account;
		if (event == null) {
			this.event = "There was an error and this transaction was halted";
		} else {
			this.event = event;
		}
	}

	public String getEvent() {
		return event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	public String toString() {
		return time + "\nACCO#" + account + "\n" + event;
	}
}

/*
How will the activity class work?
- It will be generated by basic Account functions
- It will be pulled from the DB whenever you access an Account
- It will be added to the DB whenever it is generated
- It will be read to the receipt when printed
*/