/** How are these initialized?
			If the activity is created from an Account, it should have the current timestamp,
			event determined by the calling function, and details supplied.
			If the activity is created from a database (ie, for RecentActivity polls), the
			timestamp must be pulled from the DB and converted to long, and the strings must
			be pulled.
		 **/

import java.util.Date;
import java.sql.*;

public class Activity {
	private Date date;
	private String event;

	/** Constructor for in-session creation **/
	public Activity(Connection conn, String event) {
		this.event = event;
		this.date = new Date();
		//Create timestamp, push to DB
		Timestamp timestamp = new Timestamp(date.getTime());
	}
}


/*
How will the activity class work?
- It will be generated by basic Account functions
- It will be pulled from the DB whenever you access an Account
- It will be added to the DB whenever it is generated
- It will be read to the receipt when printed

:: The Date object should be initialized from a java.sql.Timestamp
*/